dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - docker
script:
  - mvn clean package
  - docker-compose up -d karaf
  - sleep 15
  - docker-compose exec karaf bash -c "ls -la /tmp/package"
  - docker-compose exec karaf bash -c "cp /tmp/package/hello-world-1.0.0.jar /opt/apache-karaf/deploy"
  - sleep 5
  - ./support/test.sh ./tests
