version: 2.1
jobs:
  build:
    machine: true
    docker: 
      - image: circleci/openjdk:8u242-jdk
    steps:
      - checkout
      - run: mvn clean package
      - run: ls -la target
      - run: docker ps -a

